# Generated by Django 4.2.15 on 2024-11-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredients', 'verbose_name': 'ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
